---
- name: Download Wordpress Release
  get_url:
    url: http://wordpress.org/{{ wordpress.package }}
    dest: /tmp/{{ wordpress.package }}

- name: Extract wordpress into /var/www/html
  unarchive:
    src: "/tmp/{{ wordpress.package }}"
    dest: "{{ wordpress.dest_directory }}"
    remote_src: yes

- name: Send file to /etc/nginx/conf.d
  template:
    src: wp-config.php.j2
    dest: "{{ wordpress.wordpress_directory }}/wp-config.php"
    owner: root
    group: root
    mode: "0644"
    force: yes

- name: Send nginx configuration
  template:
    src: wordpress-nginx.conf.j2
    dest: "/etc/nginx/conf.d/{{ wordpress.server_name }}.conf"
    owner: root
    group: root
    mode: "0644"
    force: yes

- name: Download HyperDB
  get_url:
    url: http://downloads.wordpress.org/plugin/hyperdb.zip
    dest: /tmp/hyperdb.zip

- name: Extract wordpress into /var/www/html
  unarchive:
    src: "/tmp/hyperdb.zip"
    dest: "/tmp/"
    remote_src: yes

- name: Send hyperDB configuration
  template:
    src: db-config.php.j2
    dest: "{{ wordpress.wordpress_directory }}/db-config.php"
    owner: root
    group: root
    mode: "0644"
    force: yes

- name: Send HyperDB plugin to wordpress folder
  command: cp /tmp/hyperdb/db.php "{{ wordpress.wordpress_directory }}/wp-content/db.php"

- name: Check Nginx Configuration
  command: nginx -t

- name: Change Directory Permissions
  command: "chown -R {{ wordpress.web_user }}:{{ wordpress.web_user }} {{ wordpress.wordpress_directory }}"
  become: true

- name: Restart Nginx and PHP
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  loop:
    - nginx
    - php-fpm
# tasks file for wordpress
