---
- name: ansible-fatcs
  debug: 
    var: ansible_facts['distribution_major_version']

- name: Install php on Amazon Linux
  include: amazon_linux.yaml
  when: ansible_facts['distribution'] == "Amazon" and ansible_facts['distribution_major_version'] == "2018"
  # Support for Amazon Linux 1

- name: Configure Nginx to work with PHP-FPM
  include: nginx_support.yaml
  when: "php.nginx_support == true"
# tasks file for php